watchtower/heroes/urls.py
from django.urls import path
from . import views
# from watchtower import heroes

app_name = "heroes"
urlpatterns = [
    path('', views.index, name ='index'),
    path('<int:heroes_id>/', views.detail, name='detail'),  
    path('create/', views.create, name='create_hero'),
    path('edit/<int:heroes_id>/', views.edit, name='edit')
]

watchtower/watchtower/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('heroes/', include('heroes.urls')),
    path('', RedirectView.as_view(url='heroes/'))
]

watchtower/heroes/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Heroes (models.Model):
    
    super_hero_name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_power = models.CharField(max_length=50)
    secondary_power = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)
    
    def __str__(self):
        return self.super_hero_name

watchtower/heroes/views.py
# from typing_extensions import runtime
from django.shortcuts import redirect,render
from django.http import HttpResponse,HttpResponseRedirect
from.models import Heroes
from django.urls import reverse
# Create your views here.


def index(request):
    all_heroes = Heroes.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request,'heroes/index.html',context)

def detail(request, heroes_id):
    detail_hero = Heroes.objects.get(pk=heroes_id)
    context = {
        'detail_hero':detail_hero 
    }
    return render(request, 'heroes/detail.html', context)

def create(request):
    if request.method == 'POST':
        super_hero_name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_power = request.POST.get('primary_power')
        secondary_power = request.POST.get('secondary_power')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Heroes(super_hero_name = super_hero_name, 
        alter_ego = alter_ego, 
        primary_power = primary_power, 
        secondary_power = secondary_power, 
        catchphrase = catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('heroes:index'))
    else:
        return render(request, 'heroes/create.html')

def edit(request, heroes_id):
    if request.method == 'POST':
        new_hero = Heroes.objects.get(pk=heroes_id)
        new_hero.super_hero_name = request.POST.get('super_hero_name')
        new_hero.alter_ego = request.POST.get('alter_ego')
        new_hero.primary_power = request.POST.get('primary_power')
        new_hero.secondary_power = request.POST.get('secondary_power')
        new_hero.catchphrase = request.POST.get('catchphrase') 
        new_hero.save()
        return HttpResponseRedirect(reverse('heroes:index'))    
    
    edit_hero = Heroes.objects.get(pk=heroes_id)
    context = {
        'edit_hero': edit_hero
    }
    return render(request, 'heroes/edit.html', context)

def delete(request,heroes_id):
    if request.method =='POST':
        delete_hero = Heroes.objects.delete(pk=heroes_id)
        return HttpResponseRedirect(reverse('heroes:index'))

watchtower/heroes/templates/heroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create</title>
</head>
<body>
    <form action="{% url 'heroes:create_hero' %}" method="post">
        {% csrf_token %} <br />
        Super Hero Name: 
        <input 
        type="text" 
        name="name" 
        id="name" /><br />
        Alter ego: <input 
            type="text" 
            name="alter_ego" 
            id="alter_ego" 
        /><br />
       Primary Power:<input
            type="text"
            name="primary_power"
            id="primary_power"
        /><br />
        Secondary Power:<input
            type="text"
            name="secondary_power"
            id="secondary_power"
        /><br />
        Catchphrase:<input 
            type="text" 
            name="catchphrase" 
            id="catchphrase" /><br />
        <input type="submit" value="Add new!" />
    </form>  
</body>
</html>

watchtower/heroes/templates/heroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>details</title>
</head>
<body>
    <h1>Hero Details!</h1>
    <h2>{{detail_hero.super_hero_name}}</h2>
    <h2>{{detail_hero.alter_ego}}</h2>
    <h2>{{detail_hero.primary_power}}</h2>
    <h2>{{detail_hero.secondary_power}}</h2>
    <h2>{{detail_hero.catchphrase}}</h2>
</body>
</html>

watchtower/heroes/templates/heroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>edit</title>
</head>
<body> 
    <form action="{% url 'heroes:edit' edit_hero.id %}" method="post"> <br />
        Super Hero Name:  
        <input 
        type="text" 
        name="super_hero_name" 
        id="super_hero_name" 
        value="{{edit_hero.super_hero_name}}"/><br />
        Alter ego:<input
            type="text"
            name="alter_ego"
            id="alter_ego"
            value="{{edit_hero.alter_ego}}"/><br />
        Primary power:<input
            type="text"
            name="primary_power"
            id="primary_power"
            value="{{edit_hero.primary_power}}"/><br />
        Secondary power:<input
            type="text"
            name="secondary_power"
            id="secondary_power"
            value="{{edit_hero.secondary_power}}"/><br />
        Catchphrase:<input 
            type="text" 
            name="catchphrase" 
            id="catchphrase" 
            value="{{edit_hero.catchphrase}}"/><br />
        <input type="submit" value="Edit Hero"/>       

/body>
</html>

watchtower/heroes/templates/heroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>heroes</title>
</head>
<body>
    <h1>List of all Heroes!!</h1>
    <ul>   
        {% for heroes in all_heroes %}
        <li>
            <h2>{{heroes.super_hero_name}}</h2>
            <a href="{% url 'heroes:detail' heroes.id %}">Click for details</a>
            <a href="{% url 'heroes:edit' heroes.id %}">Edit A Hero!</a>
        </li>
        {% endfor %}
    </ul>
    <ul>   
        <h2> Other Things You Can Do!</h2>
        <li><a href="{% url 'heroes:create_hero' %}">Create New Hero!</a></li>
    </ul>
    {% load static %}
    <img src="{% static 'heroes/lobo.jpg' %}"
</body>
</html>